@startuml

skinparam componentStyle uml2

package "'Motorista' Aggregate" <<Rectangle>> {
	class Motorista <<(A,#fffab8) Aggregate Root>> {
		String nomeMotorista
		IdUsuario usuarioMotorista
		IdMotorista idMotorista
		List<IdVeiculo> veiculos
		List<IdAgendamento> historicoDeUso
	}
	class IdMotorista <<(V,DarkSeaGreen) Value Object>> {
		int idMotorista
	}
	class AlteracoesContaMotorista <<(S,DarkSeaGreen) Service>> {
		int deletarConta(IdUsuario usuarioMotorista)
		int alterarNomeMotorista(String novoNome)
	}
}
Motorista --> IdMotorista : idMotorista


@enduml
