@startuml

skinparam componentStyle uml2

package "'Fornecedor' Aggregate" <<Rectangle>> {
	class Fornecedor <<(A,#fffab8) Aggregate Root>> {
		String nomeFornecedor
		IdUsuario usuarioFornecedor
		IdFornecedor idFornecedor
		List<IdEstacao> estacoesDeRecarga
		List<IdAgendamento> historicoDeUso
	}
	class IdFornecedor <<(V,DarkSeaGreen) Value Object>> {
		int idFornecedor
	}
	class AlteracoesContaFornecedor <<(S,DarkSeaGreen) Service>> {
		int deletarConta(IdUsuario usuarioFornecedor)
		int alterarNomeFornecedor(String novoNome)
	}
}
Fornecedor --> IdFornecedor : idFornecedor


@enduml
