@startuml

skinparam componentStyle uml2

package "'Accounts' Aggregate" <<Rectangle>> {
	class ClienteAccount <<(E,DarkSeaGreen) Entity>> {
		String usernameCliente
		Cliente dadosCliente
	}
	class FornecedorAccount <<(E,DarkSeaGreen) Entity>> {
		String usernameFornecedor
		Fornecedor dadosFornecedor
	}
}


@enduml
