@startuml

skinparam componentStyle uml2

package "'Cliente' Aggregate" <<Rectangle>> {
	class Cliente <<(A,#fffab8) Aggregate Root>> {
		int idCliente
		String nomeCliente
		String emailCliente
		List<Veiculo> veiculos
	}
	class RecargasCliente <<(E,DarkSeaGreen) Entity>> {
		List<Agendamento> meusAgendamentos
		void getMinhasRecargas(List<Agendamento> meusAgendamentos)
	}
}


@enduml
