@startuml

skinparam componentStyle uml2

package "'Agendamento' Aggregate" <<Rectangle>> {
	class Agendamento <<(A,#fffab8) Aggregate Root>> {
		int idAgendamento
		int codigoLiberacaoCarregador
		DateTime horarioAgendamento
		Cliente idCliente
		Veiculo idVeiculo
		Fornecedor idFornecedor
		EstacaoRecarga idEstacao
		Carregadores tipoPlugCarregador
	}
	class Recarga <<(E,DarkSeaGreen) Entity>> {
		double energiaUtilizada
		Agendamento idAgendamento
	}
	class RealizarAgendamento <<(S,DarkSeaGreen) Service>> {
		int realizarAgendamento(DateTime horarioAgendamento, Veiculo idVeiculo, EstacaoRecarga idEstacao, Carregadores tipoPlugCarregador)
	}
	class GetCodigoLiberacao <<(S,DarkSeaGreen) Service>> {
		int getCodigoLiberacao(Agendamento idAgendamento)
	}
}
Recarga --> Agendamento : idAgendamento
legend left
  This bounded context implements the subdomain 'AgendaDomain'.
end legend


@enduml
