@startuml

skinparam componentStyle uml2

package "'Avaliacao' Aggregate" <<Rectangle>> {
	class Avaliacao <<(A,#fffab8) Aggregate Root>> {
		String[0..1] descricaoExperiencia
		IdAgendamento idAgendamento
		Avaliacoes avaliacaoDada
	}
	enum Avaliacoes {
		UM
		DOIS
		TRES
		QUATRO
		CINCO
	}
}
Avaliacao --> Avaliacoes : avaliacaoDada


@enduml
