@startuml

skinparam componentStyle uml2

package "'Notificacao' Aggregate" <<Rectangle>> {
	class Notificacao <<(E,DarkSeaGreen) Entity>> {
		String mensagem
		List<IdUsuario> destinatarios
		IdUsuario[0..1] origem
		null id
	}
}


@enduml
