@startuml

skinparam componentStyle uml2

package "'ConsultaEstacoesProximas' Aggregate" <<Rectangle>> {
	class ConsultaEstacoesProximas <<(A,#fffab8) Aggregate Root>> {
		int raioDeBusca
		Endereco enderecoAtualMotorista
		List<EstacaoDeRecarga> estacoesProximas
	}
	class SetNovoRaioDeBusca <<(S,DarkSeaGreen) Service>> {
		int setNovoRaio(int novoRaio)
	}
}


@enduml
