/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MapaImport } from './routes/mapa'
import { Route as DetalhesEstacaoImport } from './routes/detalhesEstacao'
import { Route as AgendamentosImport } from './routes/Agendamentos'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const MapaRoute = MapaImport.update({
  path: '/mapa',
  getParentRoute: () => rootRoute,
} as any)

const DetalhesEstacaoRoute = DetalhesEstacaoImport.update({
  path: '/detalhesEstacao',
  getParentRoute: () => rootRoute,
} as any)

const AgendamentosRoute = AgendamentosImport.update({
  path: '/Agendamentos',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/Agendamentos': {
      id: '/Agendamentos'
      path: '/Agendamentos'
      fullPath: '/Agendamentos'
      preLoaderRoute: typeof AgendamentosImport
      parentRoute: typeof rootRoute
    }
    '/detalhesEstacao': {
      id: '/detalhesEstacao'
      path: '/detalhesEstacao'
      fullPath: '/detalhesEstacao'
      preLoaderRoute: typeof DetalhesEstacaoImport
      parentRoute: typeof rootRoute
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/Agendamentos': typeof AgendamentosRoute
  '/detalhesEstacao': typeof DetalhesEstacaoRoute
  '/mapa': typeof MapaRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/Agendamentos': typeof AgendamentosRoute
  '/detalhesEstacao': typeof DetalhesEstacaoRoute
  '/mapa': typeof MapaRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/Agendamentos': typeof AgendamentosRoute
  '/detalhesEstacao': typeof DetalhesEstacaoRoute
  '/mapa': typeof MapaRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Agendamentos' | '/detalhesEstacao' | '/mapa' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Agendamentos' | '/detalhesEstacao' | '/mapa' | '/about'
  id:
    | '__root__'
    | '/'
    | '/Agendamentos'
    | '/detalhesEstacao'
    | '/mapa'
    | '/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AgendamentosRoute: typeof AgendamentosRoute
  DetalhesEstacaoRoute: typeof DetalhesEstacaoRoute
  MapaRoute: typeof MapaRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AgendamentosRoute: AgendamentosRoute,
  DetalhesEstacaoRoute: DetalhesEstacaoRoute,
  MapaRoute: MapaRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/Agendamentos",
        "/detalhesEstacao",
        "/mapa",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/Agendamentos": {
      "filePath": "Agendamentos.tsx"
    },
    "/detalhesEstacao": {
      "filePath": "detalhesEstacao.tsx"
    },
    "/mapa": {
      "filePath": "mapa.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
