@startuml

skinparam componentStyle uml2

component [GerenciamentoFornecimentoContext]
note right of [GerenciamentoFornecimentoContext]
O contexto de gerenciamento de 
fornecedores é responsável por 
armazenar os dados dos fornecedores 
e suas estações. 
end note
component [GerenciamentoClientelaContext]
note right of [GerenciamentoClientelaContext]
O contexto de gerenciamento de 
clientes é responsável por armazenar 
os dados dos clientes e de seus 
veículos e agendamentos. 
end note
component [GerenciamentoAgendamentosContext]
note right of [GerenciamentoAgendamentosContext]
O contexto de gerenciamento de 
agendamentos é responsável por 
gerenciar todos os dados referentes 
ao processo de agendar as estações, 
inclusive oferecendo serviços 
de consulta e validação de datas 
e horarios. 
end note
component [GerenciamentoAutenticacaoContext]
note right of [GerenciamentoAutenticacaoContext]
O contexto de gerenciamento de 
autenticacao é uma aplicação que 
permite aos usuários realizarem 
login e alterarem informações 
sobre seus dados, veiculos ou 
estações. 
end note

interface "Customer-Supplier" as GerenciamentoAgendamentosContext_to_GerenciamentoFornecimentoContext
[GerenciamentoFornecimentoContext] --> GerenciamentoAgendamentosContext_to_GerenciamentoFornecimentoContext : Supplier
GerenciamentoAgendamentosContext_to_GerenciamentoFornecimentoContext <.. [GerenciamentoAgendamentosContext] : Customer 

interface "Customer-Supplier" as GerenciamentoAgendamentosContext_to_GerenciamentoClientelaContext
[GerenciamentoClientelaContext] --> GerenciamentoAgendamentosContext_to_GerenciamentoClientelaContext : Supplier
GerenciamentoAgendamentosContext_to_GerenciamentoClientelaContext <.. [GerenciamentoAgendamentosContext] : Customer 

[GerenciamentoFornecimentoContext]<-->[GerenciamentoAutenticacaoContext] : Partnership

[GerenciamentoClientelaContext]<-->[GerenciamentoAutenticacaoContext] : Partnership



@enduml
